development:
  dialect: postgres
  database: mile_high_development
  user: brianwynn
  password: DEV_DATABASE_PASSWORD
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mile_high_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mile_high_production?sslmode=disable"}}
